jwt:
  header: Authorization
  param: token
  secret: m6sXDUKZSY154e9Nm6sXDUKZSY154e9N
  expiration: 604800000
  prefix: Bearer
  route:
    authentication:
      path: auth
      token: token
      refresh: refresh